# Generated by Django 5.1.5 on 2025-07-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, ' ★ ☆ ☆ ☆ ☆'), (2, ' ★ ★ ☆ ☆ ☆'), (3, ' ★ ★ ★ ☆ ☆'), (4, ' ★ ★ ★ ★ ☆'), (5, ' ★ ★ ★ ★ ★')]),
        ),
    ]
