# Generated by Django 5.1.5 on 2025-08-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_image_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
