# Generated by Django 5.1.5 on 2025-07-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_by', models.EmailField(max_length=254)),
                ('sent_to', models.TextField(null=True)),
                ('about', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
