# Generated by Django 5.1.5 on 2025-06-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_message_sent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='about',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
