# Generated by Django 5.1.5 on 2025-07-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_user_firstname_user_lastname_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
