# Generated by Django 5.1.5 on 2025-07-21 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
