# Generated by Django 5.1.5 on 2025-07-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='000 000 0000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
