# Generated by Django 5.1.5 on 2025-07-21 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_remove_user_firstname_remove_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
