# Generated by Django 5.1.5 on 2025-09-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_cartmodel_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='total_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
